### ISSUE TITLE
Google OpenID 2.0 authentication deprecated

### ISSUE THREAD

**Issue by flyte** [ASKBOT/askbot-devel#257]
Google has closed its OpenID 2.0 implementation to new hosts, which breaks the ability to use it for new installations of Askbot: https://developers.google.com/+/api/auth-migration#timetable

I believe the necessary action is to change to using the Google+ sign-in system: https://developers.google.com/+/api/auth-migration#oid2

Or apparently without using the Google+ system which they allude to by saying "You can still hand roll your integration to Google using the OpenID Connect protocol if you prefer" here: http://googledevelopers.blogspot.co.uk/2014/02/welcome-openid-connect.html

**Comment by nilesjohnson** [comment]
We are now close to the end of the deprecation period.  Does upgrading to askbot 0.7.51 solve this problem?  Do accounts created under the old system work under the new system?

**Comment by nilesjohnson** [comment]
I have now tested this myself, at http://ask.sagemath.org.  There is a config in the django admin section which allows you to switch to G+ login instead of "Google (deprecated)".  But if you sign in with G+, askbot creates a *new* user, rather that associating the G+ account with the old Google sign-in.  

How can we associate new G+ sign-in with old "Google (deprecated)" accounts!?

**Comment by evgenyfadeev** [comment]
I wasn't able to find a way to migrate users from Google OpenId to G+

On Wed, Apr 1, 2015 at 11:12 AM, Niles Johnson <notifications@github.com>
wrote:

> I have now tested this myself, at http://ask.sagemath.org. There is a
> config in the django admin section which allows you to switch to G+ login
> instead of "Google (deprecated)". But if you sign in with G+, askbot
> creates a *new* user, rather that associating the G+ account with the old
> Google sign-in.
>
> How can we associate new G+ sign-in with old "Google (deprecated)"
> accounts!?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/257#issuecomment-88499946>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by nilesjohnson** [comment]
uh oh :(

I have been able to do this for my own user by flipping back and forth between the old Google sign-in and the G+ signin:

* Sign in with the old Google signin
* use "manage login methods"  (/account/signin/) to add a password to my account
* Go to the django admin and switch to G+ login
* sign out, and then back in using password
* use "manage login methods" again to add G+ to my account

Is there really no way to automate this, or even part of this, for ordinary users?

Do you have a different plan for what to do when Google shuts the service off?

**Update**

Here are two possible workarounds I can imagine.  Do you know if they will really work?

1. Enable *both* Google and G+ login, so that people can directly associate a G+ login without having to go through the intermediate step of creating a password.  This will be problematic though because it will be confusing for users, and because once Google authentication is disabled no one will be able to use it anyway.

2.  Send everyone with Google id a temporary password to their gmail address.  This will also be confusing, and possibly a security risk.  Maybe a button like password recovery, which will generate a new password and send it to their gmail address?

**Comment by nilesjohnson** [comment]
Does this guide not apply to askbot?

https://developers.google.com/+/api/auth-migration#oid2

**Comment by evgenyfadeev** [comment]
I've tried those instructions using server side openid and it did not work.

I guess this method can be tried too, maybe there is a small
detail that I've missed in the server side openid implementation.

On Wed, Apr 1, 2015 at 12:06 PM, Niles Johnson <notifications@github.com>
wrote:

> Does this guide not apply to askbot?
>
> https://developers.google.com/+/api/auth-migration#oid2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/257#issuecomment-88517381>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by nilesjohnson** [comment]
ok; I think it will be important for us to figure this out, or we'll loose the Google id users (which are most of our users!).  I don't know where to get started with those instructions though.

**Comment by evgenyfadeev** [comment]
Niles, I think it works now, please try the master branch.

On Thu, Apr 2, 2015 at 8:42 AM, Niles Johnson <notifications@github.com>
wrote:

> ok; I think it will be important for us to figure this out, or we'll loose
> the Google id users (which are most of our users!). I don't know where to
> get started with those instructions though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/257#issuecomment-88873281>.
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by stapelberg** [comment]
To make it clearer to other people stumbling over this:

askbot 0.7.52 contains commit https://github.com/ASKBOT/askbot-devel/commit/0e090805715157a1f9acf2f497b30ae7c0ca4c97 which handles migration by converting the account association from an openid URL to a google-plus userid automatically. Once you enabled google-plus sign in (“Settings → Login, Users & Communication → Login provider setings → Google Login”), users will be presented with a g+ sign-in button instead of a (non-working) google login button and can just sign in with their regular account. The migration happens transparently.
