### ISSUE TITLE
Links at end of comments are broken by </p> tag

### ISSUE THREAD

**Issue by dfarrell07** [ASKBOT/askbot-devel#324]
Links at the end of comments on questions/answers get a `</p>` tag appended to them, which breaks the links. The comment on [this question](https://ask.opendaylight.org/question/966/integrating-opendaylight-using-devstack-by-default-increases-host-memory/) is an example. It resolves to `https://bugs.opendaylight.org/</p>`, which clearly 404s.

**Comment by slel** [comment]
Is this really fixed? What version of Askbot has this?

**Comment by slel** [comment]
@evgenyfadeev can you reopen this issue? It doesn't seem to be fixed.
Or maybe the fix is not live at "Ask Askbot", see last link in my comment at
http://askbot.org/en/question/8878/reasonable-site-load-time-with-pingdom/?answer=8882#post-id-8882

**Comment by slel** [comment]
Ask Sage at https://ask.sagemath.org/ currently runs Askbot 0.7.56,
and it seems that for newly created comments, links at the end of
comments don't get the extra trailing html end-of-paragraph ( `</p>`)
tag, so this indeed appears to be fixed, but one should not that old
posts are not fixed by upgrading to a new version, one needs to edit
them in order for the links at the end of comments to start working.

**Comment by slel** [comment]
But "Ask Askbot" at https://askbot.org/ currently runs Askbot 0.7.58
and the problem persists there... So not clear this issue is fixed really.
